on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: nhhhhhh
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./
        with:
          who-to-greet: "me"